# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Memetitle',
            field=models.CharField(default=True, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
